### ISSUE TITLE
Tuple object has no attribute items

### ISSUE THREAD

**Issue by s90** [freeipa/freeipa-healthcheck#103]
Hi,
I use ipa-healthcheck on centos-8 and have such output:

  {
    "source": "ipahealthcheck.ipa.certs",
    "check": "IPACertRevocation",
    "result": "CRITICAL",
    "uuid": "a2e82449-934a-444c-be68-66cdd99b8e0c",
    "when": "20191212104501Z",
    "duration": "0.001813",
    "kw": {
      "exception": "'tuple' object has no attribute 'items'"
    }
  }

Please advise how to fix it.

**Comment by rcritten** [comment]
I'm so sorry for missing this now more than two year old issue.

I'm not sure what to do with it at this point.
