### ISSUE TITLE
IPACertmongerExpirationCheck fails with reissued certificates

### ISSUE THREAD

**Issue by rippiedoos** [freeipa/freeipa-healthcheck#150]
I've reissued the HTTPS and LDAPS certificates to add a Subject Alt Name for a floating IP on my two FreeIPA Master Servers. I've used these to user-list-threads to do it:
- https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/6FISBEB4UCE5IGW2XMVVYRR6Q2WOZG46/
- https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/BVJEMTQTFBU2XGVZCQDSVXS5ZJNXIZCK/

In essence I performed a resubmit of two certificates (per node) that where not expired and good, to add a SAN to the certificates. But now I have 4 expired certificates with unknown Request ID's:
```
  {
    "source": "ipahealthcheck.ipa.certs",
    "check": "IPACertmongerExpirationCheck",
    "result": "ERROR",
    "uuid": "b798d01d-6fb1-4be5-902e-d3ae862d2e6d",
    "when": "20200818205342Z",
    "duration": "0.035975",
    "kw": {
      "key": "20200818200323",
      "expiration_date": "19700101000000Z",
      "msg": "Request id 20200818200323 expired on 19700101000000Z"
    }
  },
```
But I have no Request ID that matches this ID, only one that starts with 202004 (install-date of the system). And the Request ID that is shown in this error is the current date. I did a total of 4 resubmits and I guess these are the 4 errors.

# Used software
Oracle Linux 8.2 x86_64
FreeIPA 4.8.4
ipa-healthcheck 0.4

**Comment by rcritten** [comment]
Sorry for the delay. This suggests that the tracking request is not storing a copy of the certificate as it should. Are you saying that there is no certmonger request id of "20200818200323"?

**Comment by rippiedoos** [comment]
Yes, I'm having the exact same issues as mentioned here: https://bugzilla.redhat.com/show_bug.cgi?id=1852244#c15

I've not added them back to certmonger, but I have 2 environments where this exact same thing happened. Installed on 8.1 and upgraded to 8.2.

Both installed with the DNS-option.

**Comment by rcritten** [comment]
Follow the instructions in the Doc-text in the BZ:

dnf install ipa-healthcheck-0.4

**Comment by rcritten** [comment]
We seem to have lost traction on this, closing.
