### ISSUE TITLE
how about pylint?

### ISSUE THREAD

**Issue by stanislavlevin** [freeipa/freeipa-healthcheck#162]
Current pylint warnings/recommendations/errors:
[pylint.log](https://github.com/freeipa/freeipa-healthcheck/files/5501966/pylint.log)

@rcritten, I can fix/ignore these if you want Pylint.

**Comment by rcritten** [comment]
Sure, that'd be great. I toyed with a bit a while back but I ended up thinking it would require ipa-like pylint plugin and trying to keep them in sync...
