### ISSUE TITLE
Return value isn't non-zero on error

### ISSUE THREAD

**Issue by rcritten** [freeipa/freeipa-healthcheck#31]
I'm seeing a failure in the replication checking plugin that is correctly reporting an error but not setting the return code to 1.

```
# ipa-healthcheck --failures-only
[
  {
    "source": "ipahealthcheck.ds.replication",
    "check": "ReplicationConflictCheck",
    "severity": 1,
    "uuid": "28cd5454-b4ed-4eed-b5c7-6bfc818d77d7",
    "when": "20190624183048Z",
    "duration": "0.000035",
    "kw": {
      "exception": "type object 'LDAPClient' has no attribute 'from_realm'"
    }
  }
]
# echo $?
0
```
So we need to fix the underlying exception and ensure that exceptions cause a non-zero error to be returned.

**Comment by rcritten** [comment]
Aha, I'm running 4.7.2 not master.

**Comment by rcritten** [comment]
https://github.com/freeipa/freeipa-healthcheck/pull/33

**Comment by fcami** [comment]
Closing as https://github.com/freeipa/freeipa-healthcheck/pull/33 is merged.
