### ISSUE TITLE
add check that sssd.conf on IPA master uses ipa provider for the IPA domain

### ISSUE THREAD

**Issue by abbra** [freeipa/freeipa-healthcheck#83]
When checking `sssd.conf` on IPA masters, we need to make sure that provider for the primary IPA domain must be `ipa`, not anything else (like `ad`). Finding this through sosreport for environments where you aren't allowed to pull out data is tough.

**Comment by rcritten** [comment]
To be clear you want to enforce that in the domain section for the IPA domain id_provider == 'ipa'?
What about the other options there? auth_provider, chpass_provider, and access_provider?

**Comment by abbra** [comment]
Right. I think those other parameters need to be enforced as well.
